"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from corsheaders.defaults import default_headers
from dotenv import load_dotenv
from mongoengine import connect

# -----------------------------------------------------------------------------
# Base Configuration
# -----------------------------------------------------------------------------

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env if available
if load_dotenv is not None:
    env_file = BASE_DIR / ".env"
    if env_file.exists():
        load_dotenv(env_file)

# -----------------------------------------------------------------------------
# Security & Debug Settings
# -----------------------------------------------------------------------------

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-only-do-not-use")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True").lower() in ("1", "true", "yes", "on")

# Configure Allowed Hosts
# Reads from DJANGO_ALLOWED_HOSTS env var (comma-separated).
# Defaults to localhost/127.0.0.1 for development if not set.
_allowed_hosts_env = os.environ.get("DJANGO_ALLOWED_HOSTS", "").strip()
if _allowed_hosts_env:
    ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_env.replace(";", ",").split(",") if h.strip()]
else:
    # Safe defaults for local dev and university server
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0', 'turing.cs.olemiss.edu']
    # If DEBUG is off, ensure we have valid hosts to prevent CommandError
    if not DEBUG and not ALLOWED_HOSTS:
        ALLOWED_HOSTS = ['localhost', '127.0.0.1', '0.0.0.0']

# -----------------------------------------------------------------------------
# CORS (Cross-Origin Resource Sharing) Configuration
# -----------------------------------------------------------------------------

# Define which frontend origins can access this API.
CORS_ALLOWED_ORIGINS = [
    # Local development (Vite/React default ports)
    "http://localhost:5173",
    "http://localhost:5174",
    "http://localhost:3000",
    "http://localhost:3003",
    "http://127.0.0.1:5173",
    "http://127.0.0.1:5174",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:3003",
    # Staging / Production server
    # Allow both HTTP and HTTPS for university server and explicit port 3003
    "http://turing.cs.olemiss.edu",
    "http://turing.cs.olemiss.edu:3003",
]

CORS_ALLOW_CREDENTIALS = True

# Trusted origins for CSRF protection
CSRF_TRUSTED_ORIGINS = CORS_ALLOWED_ORIGINS

# Allow custom headers used by the frontend (e.g., authentication tokens)
CORS_ALLOW_HEADERS = list(default_headers) + [
    "x-user-id",
    "userID",
    "UserID",
    "authorization",
    "x-csrftoken",
    "x-csrf-token",
    "content-disposition",
]

# Expose headers that clients might need to read programmatically
CORS_EXPOSE_HEADERS = [
    "x-user-id",
    "content-disposition",
]

# Permissive CORS mode for development (Avoids strict blocking during testing)
RELAXED_CORS = os.environ.get("CORS_RELAXED", "True").lower() in ("1", "true", "yes", "on")
if DEBUG or RELAXED_CORS:
    # Allow any HTTP/HTTPS origin (regex avoids wildcard issues with credentials)
    CORS_ALLOWED_ORIGIN_REGEXES = [r"^https?://.*$"]
    CORS_ALLOW_PRIVATE_NETWORK = True  # Supports local network requests

# -----------------------------------------------------------------------------
# Application Definition
# -----------------------------------------------------------------------------

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "authentication",
    "users",
    "corsheaders",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",  # Must be near the top
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"

# -----------------------------------------------------------------------------
# Database Configuration
# -----------------------------------------------------------------------------

# Primary Data Store: MongoDB via MongoEngine
# Connection logic supports both direct URI and discrete parameter configuration.

def _env_bool(name: str, default: bool = False) -> bool:
    """Helper to parse boolean environment variables."""
    v = os.environ.get(name)
    if v is None:
        return default
    return v.strip().lower() in ("1", "true", "yes", "on")

_host = os.environ.get('MONGODB_HOST', 'localhost')
_db = os.environ.get('MONGODB_DB', 'group3f25_db')
_username = os.environ.get('MONGODB_USERNAME', '')
_password = os.environ.get('MONGODB_PASSWORD', '')
_auth_source = os.environ.get('MONGODB_AUTH_SOURCE', os.environ.get('MONGODB_DB', 'admin'))

# Determine effective port (Default 27017 for standard MongoDB)
_port_env = os.environ.get('MONGODB_PORT')
try:
    _port_effective = int(_port_env) if _port_env is not None else 27017
except Exception:
    _port_effective = 27017

# Settings dictionary for discrete parameters
MONGODB_SETTINGS = {
    'host': _host,
    'port': _port_effective,
    'db': _db,
    'username': _username,
    'password': _password,
    'authentication_source': _auth_source,
}

# Optional direct connection URI override
MONGODB_URI = os.environ.get('MONGODB_URI', None)

# Establish connection
try:
    if MONGODB_URI:
        connect(host=MONGODB_URI, alias='default')
    else:
        connect(**MONGODB_SETTINGS)

    # Health check: Ping the server to ensure connectivity
    try:
        from mongoengine.connection import get_connection
        _conn = get_connection(alias='default')
        _conn.admin.command('ping')
        print("✅ MongoDB ping succeeded; connection is healthy")
    except Exception as ping_err:
        raise RuntimeError(f"MongoDB ping failed: {ping_err}")
except Exception as e:
    print(f"⚠️ MongoDB connection failed: {e}")
    print("App will continue but MongoDB features (Users, Claims) won't work.")

# Secondary Data Store: SQLite
# Retained for Django's internal features (Admin, Sessions, Auth, ContentTypes)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# -----------------------------------------------------------------------------
# Password & Authentication
# -----------------------------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# Use Argon2 for secure password hashing
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
]

# -----------------------------------------------------------------------------
# Internationalization & Static Files
# -----------------------------------------------------------------------------

LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

STATIC_URL = "static/"
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# -----------------------------------------------------------------------------
# Third-Party & Custom Settings
# -----------------------------------------------------------------------------

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
}

# Company Configuration
# Domain used to auto-classify users as 'employee' or 'customer' during login
COMPANY_EMAIL_DOMAIN = os.environ.get("COMPANY_EMAIL_DOMAIN", "lyceum-ledgers.com")

# Email Backend Configuration (SMTP)
EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True").lower() in ("1", "true", "yes", "on")
EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", "False").lower() in ("1", "true", "yes", "on")
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER or "no-reply@lyceum-ledgers.com")

# Password Reset URL
# Used in email templates to direct users to the frontend reset page
PASSWORD_RESET_BASE_URL = os.environ.get("PASSWORD_RESET_BASE_URL", "")