"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
try:
    from dotenv import load_dotenv
except Exception:
    load_dotenv = None

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env if available
if load_dotenv is not None:
    env_file = BASE_DIR / ".env"
    if env_file.exists():
        load_dotenv(env_file)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read from environment; fallback only for local dev.
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-only-do-not-use")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "True").lower() in ("1", "true", "yes", "on")

# Allow both local development and Turing server
ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'turing.cs.olemiss.edu',]

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "authentication",
    "users",
    "corsheaders",
]
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "backend.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# MongoDB connection for MongoEngine
from mongoengine import connect

# Optionally start an SSH tunnel (for remote MongoDB) before connecting.
try:
    from .connection_ssh import ensure_ssh_tunnel_if_enabled
    ensure_ssh_tunnel_if_enabled()
except Exception as e:
    print(f"SSH tunnel not started: {e}")

# MongoDB connection settings (dict-based)
MONGODB_SETTINGS = {
    'host': os.environ.get('MONGODB_HOST', 'localhost'),
    'port': int(os.environ.get('MONGODB_PORT', 27017)),
    'db': os.environ.get('MONGODB_DB', 'group3f25_db'),
    'username': os.environ.get('MONGODB_USERNAME', ''),
    'password': os.environ.get('MONGODB_PASSWORD', ''),
    # When users are defined in a specific database
    'authentication_source': os.environ.get('MONGODB_AUTH_SOURCE', os.environ.get('MONGODB_DB', 'admin')),
}


MONGODB_URI = os.environ.get('MONGODB_URI', None)

# Connect to MongoDB (with ping verification)
try:
    if MONGODB_URI:
        connect(host=MONGODB_URI, alias='default')
    else:
        connect(**MONGODB_SETTINGS)

    # Verify the connection by pinging the server
    try:
        from mongoengine.connection import get_connection  # type: ignore
        _conn = get_connection(alias='default')
        _conn.admin.command('ping')
        print("✅ MongoDB ping succeeded; connection is healthy")
    except Exception as ping_err:
        raise RuntimeError(f"MongoDB ping failed: {ping_err}")
except Exception as e:
    print(f"⚠️ MongoDB connection failed: {e}")
    print("App will continue but MongoDB features won't work")

# Keep SQLite for Django's built-in features (admin, sessions, etc.)
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
}

# Company domain configuration (used to classify employee vs. customer)
COMPANY_EMAIL_DOMAIN = os.environ.get("COMPANY_EMAIL_DOMAIN", "lyceum-ledgers.com")

# Email (SMTP) configuration
# These should be set via environment variables or a local .env file.
# Example for Gmail (App Password required):
# EMAIL_HOST=smtp.gmail.com
# EMAIL_PORT=587
# EMAIL_USE_TLS=True
# EMAIL_HOST_USER=your_account@gmail.com
# EMAIL_HOST_PASSWORD=your_app_password
EMAIL_BACKEND = os.environ.get("EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend")
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 587))
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "True").lower() in ("1", "true", "yes", "on")
EMAIL_USE_SSL = os.environ.get("EMAIL_USE_SSL", "False").lower() in ("1", "true", "yes", "on")
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER or "no-reply@lyceum-ledgers.com")

# Base URL for password reset links sent to users.
# If you have a frontend, set this to something like
# https://app.example.com/reset-password?token=
PASSWORD_RESET_BASE_URL = os.environ.get("PASSWORD_RESET_BASE_URL", "")

# For production deployment on Turing server (turing.cs.olemiss.edu)
# You'll need to update these when deploying:
# - DEBUG = False
# - SECRET_KEY = 'your-production-secret-key'
# - DATABASES = { your production database settings }
# - ALLOWED_HOSTS = ['turing.cs.olemiss.edu']
